"use client";

import { useEffect } from "react";
import { useLocale } from "@/components/LocaleProvider";
import { useMatch } from "./useMatch";
import { CheckCircle, Trophy } from "@phosphor-icons/react/dist/ssr";
import Loader from "@/components/ui/Loader";

interface MatchPracticeProps {
  initialMaterialId?: string;
  autoMode?: boolean;
  trainingMode?: boolean;
  queueIds?: string[];
  aiMode?: boolean;
  aiTopic?: string;
  pairType?: "translation" | "semantic" | "definition";
}

export default function MatchPractice({
  initialMaterialId,
  autoMode = false,
  trainingMode = false,
  queueIds = [],
  aiMode = false,
  aiTopic = "",
  pairType = "translation"
}: MatchPracticeProps) {
  const { t, locale } = useLocale();
  const {
    materials,
    activeMaterial,
    left,
    right,
    selectedLeft,
    matched,
    awarded,
    points,
    loading,
    trainingActive,
    queue,
    queueIndex,
    loadMaterials,
    loadAutoGenerated,
    selectMaterial,
    handleLeftClick,
    handleRightClick,
    resetMatches,
    checkCompletion,
    submitAttempt,
    startTraining,
    goToNextInQueue,
    goToPreviousInQueue,
    generateAI
  } = useMatch();

  useEffect(() => {
    if (aiMode && aiTopic) {
      generateAI(aiTopic, pairType, locale);
    } else if (autoMode) {
      loadAutoGenerated(10);
    } else {
      loadMaterials();
    }
  }, [aiMode, aiTopic, autoMode, generateAI, loadAutoGenerated, loadMaterials, locale, pairType]);

  useEffect(() => {
    if (materials.length === 0 || autoMode) return;

    if (trainingMode && queueIds.length > 0) {
      startTraining(queueIds);
    } else if (initialMaterialId) {
      selectMaterial(initialMaterialId);
    }
  }, [materials, autoMode, trainingMode, queueIds, initialMaterialId, selectMaterial, startTraining]);

  const isComplete = checkCompletion();
  const matchedCount = Object.keys(matched).length;
  const totalCount = left.length;

  const handleSubmit = async () => {
    await submitAttempt();
  };

  if (!activeMaterial) {
    return (
      <div className="flex h-64 items-center justify-center">
        <Loader label={t.common.loading} />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="rounded-3xl border border-ink/10 bg-paper/80 p-6 shadow-soft">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <h2 className="text-2xl font-semibold">{activeMaterial.title}</h2>
            <p className="mt-1 text-sm text-ink/60">
              {activeMaterial.level} · {t.workbook.matchTitle}
            </p>
          </div>
          <div className="flex items-center gap-3">
            <span className="text-sm text-ink/60">
              {matchedCount} / {totalCount} {t.workbook.matchMatched}
            </span>
            {trainingActive && queue.length > 1 && (
              <span className="rounded-full border border-ink/10 bg-paper px-3 py-1 text-xs">
                {queueIndex + 1} / {queue.length}
              </span>
            )}
          </div>
        </div>
      </div>

      {/* Matching Grid */}
      <div className="rounded-3xl border border-ink/10 bg-paper/80 p-6 shadow-soft">
        <div className="grid gap-6 md:grid-cols-2">
          {/* Left Column */}
          <div>
            <p className="mb-3 text-xs uppercase tracking-[0.3em] text-ink/40">
              {t.workbook.matchLeft}
            </p>
            <div className="space-y-2">
              {left.map((item, idx) => {
                const isMatched = matched[item] !== undefined;
                const isSelected = selectedLeft === item;

                return (
                  <button
                    key={`left-${idx}`}
                    onClick={() => !isMatched && handleLeftClick(item)}
                    disabled={isMatched}
                    className={`w-full rounded-2xl border px-4 py-3 text-left text-sm transition ${
                      isMatched
                        ? "border-moss/40 bg-moss/10 text-moss"
                        : isSelected
                          ? "border-ink bg-ink/10"
                          : "border-ink/10 bg-paper hover:border-ink/30"
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span className="font-semibold">{item}</span>
                      {isMatched && <CheckCircle weight="fill" className="h-5 w-5 text-moss" />}
                    </div>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Right Column */}
          <div>
            <p className="mb-3 text-xs uppercase tracking-[0.3em] text-ink/40">
              {t.workbook.matchRight}
            </p>
            <div className="space-y-2">
              {right.map((item, idx) => {
                const matchedLeftKey = Object.keys(matched).find((key) => matched[key] === item);
                const isMatched = matchedLeftKey !== undefined;

                return (
                  <button
                    key={`right-${idx}`}
                    onClick={() => !isMatched && handleRightClick(item)}
                    disabled={isMatched}
                    className={`w-full rounded-2xl border px-4 py-3 text-left text-sm transition ${
                      isMatched
                        ? "border-moss/40 bg-moss/10 text-moss"
                        : "border-ink/10 bg-paper hover:border-ink/30"
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span>{item}</span>
                      {isMatched && <CheckCircle weight="fill" className="h-5 w-5 text-moss" />}
                    </div>
                  </button>
                );
              })}
            </div>
          </div>
        </div>
      </div>

      {/* Results & Actions */}
      <div className="rounded-3xl border border-ink/10 bg-paper/80 p-6 shadow-soft">
        <div className="flex flex-wrap items-center gap-4">
          {/* Reset Button */}
          <button
            onClick={resetMatches}
            disabled={matchedCount === 0}
            className="rounded-full border border-ink/20 px-6 py-2 text-sm font-semibold text-ink transition hover:bg-ink/5 disabled:opacity-50"
          >
            {t.workbook.matchReset}
          </button>

          {/* Submit Button */}
          {isComplete && (
            <button
              onClick={handleSubmit}
              disabled={awarded}
              className="rounded-full bg-ink px-6 py-2 text-sm font-semibold text-paper transition hover:bg-ink/90 disabled:opacity-50"
            >
              {awarded ? t.workbook.matchAwarded : t.workbook.matchCheck}
            </button>
          )}

          {/* Points */}
          {points !== null && (
            <div className="flex items-center gap-2">
              <Trophy weight="fill" className="h-6 w-6 text-gold" />
              <span className="text-sm font-semibold text-moss">
                +{points} {t.workbook.points}
              </span>
            </div>
          )}

          {/* Training Navigation */}
          {trainingActive && queue.length > 1 && (
            <div className="ml-auto flex items-center gap-2">
              <button
                onClick={goToPreviousInQueue}
                disabled={queueIndex === 0}
                className="rounded-full border border-ink/20 px-4 py-2 text-xs font-semibold text-ink disabled:opacity-50"
              >
                ← {t.workbook.prev}
              </button>
              <button
                onClick={goToNextInQueue}
                disabled={queueIndex >= queue.length - 1}
                className="rounded-full border border-ink/20 px-4 py-2 text-xs font-semibold text-ink disabled:opacity-50"
              >
                {t.workbook.next} →
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
