import { useCallback, useState } from "react";

export interface MatchPair {
  left: string;
  right: string;
}

export interface MatchMaterial {
  _id: string;
  title: string;
  level: string;
  content: {
    pairs: MatchPair[];
    shuffle?: boolean;
    source?: string;
  };
}

export function useMatch() {
  const [materials, setMaterials] = useState<MatchMaterial[]>([]);
  const [activeMaterialId, setActiveMaterialId] = useState<string | null>(null);
  const [left, setLeft] = useState<string[]>([]);
  const [right, setRight] = useState<string[]>([]);
  const [selectedLeft, setSelectedLeft] = useState<string | null>(null);
  const [matched, setMatched] = useState<Record<string, string>>({});
  const [awarded, setAwarded] = useState(false);
  const [points, setPoints] = useState<number | null>(null);
  const [score, setScore] = useState<number | null>(null);
  const [loading, setLoading] = useState(false);

  // Training mode
  const [trainingActive, setTrainingActive] = useState(false);
  const [queue, setQueue] = useState<string[]>([]);
  const [queueIndex, setQueueIndex] = useState(0);

  // Auto-generation mode
  const [autoEnabled, setAutoEnabled] = useState(false);
  const [autoLoading, setAutoLoading] = useState(false);
  const [autoMaterial, setAutoMaterial] = useState<MatchMaterial | null>(null);
  const [autoTypes, setAutoTypes] = useState<string[]>(["verbs", "adverbs", "adjectives"]);
  const [autoLastUsed, setAutoLastUsed] = useState<string | null>(null);

  const activeMaterial = materials.find((m) => m._id === activeMaterialId) || autoMaterial || null;

  const shuffle = useCallback(<T,>(arr: T[]): T[] => {
    const copy = [...arr];
    for (let i = copy.length - 1; i > 0; i -= 1) {
      const j = Math.floor(Math.random() * (i + 1));
      [copy[i], copy[j]] = [copy[j], copy[i]];
    }
    return copy;
  }, []);

  const initializeMaterial = useCallback((material: MatchMaterial | null) => {
    if (!material) return;

    const pairs = material.content?.pairs || [];
    const leftItems = pairs.map((pair) => String(pair.left));
    const rightItems = pairs.map((pair) => String(pair.right));
    const shouldShuffle = material.content?.shuffle !== false;

    setLeft(shouldShuffle ? shuffle(leftItems) : leftItems);
    setRight(shouldShuffle ? shuffle(rightItems) : rightItems);
    setMatched({});
    setSelectedLeft(null);
    setAwarded(false);
    setPoints(null);
    setScore(null);
  }, [shuffle]);

  const loadMaterials = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/exercises?type=match&level=A1");
      if (!res.ok) return;
      const data = await res.json().catch(() => ({}));
      const items = data.items || [];
      setMaterials(items);
      if (items.length > 0) {
        setActiveMaterialId((prev) => {
          if (prev) return prev;
          initializeMaterial(items[0]);
          return items[0]._id;
        });
      }
    } finally {
      setLoading(false);
    }
  }, [initializeMaterial]);

  const loadAutoGenerated = useCallback(async (count: number = 10) => {
    setAutoLoading(true);
    try {
      const params = new URLSearchParams();
      params.set("count", String(Math.min(count, 20)));
      if (autoTypes.length > 0) {
        params.set("types", autoTypes.join(","));
      }

      const res = await fetch(`/api/words/random?${params.toString()}`);
      const data = await res.json().catch(() => ({}));
      const items = Array.isArray(data.items) ? data.items : [];

      const pairs = items
        .filter((item: any) => item?.pl && item?.uk)
        .map((item: any) => ({ left: String(item.pl), right: String(item.uk) }));

      if (pairs.length === 0) {
        setAutoEnabled(false);
        setAutoMaterial(null);
        return;
      }

      const now = new Date().toISOString();
      setAutoLastUsed(now);
      localStorage.setItem("match_auto_last_used", now);

      const material: MatchMaterial = {
        _id: "__auto__",
        title: "Auto-generated",
        level: "A1",
        content: { pairs, shuffle: true, source: "dictionary" }
      };

      setAutoMaterial(material);
      setAutoEnabled(true);
      setActiveMaterialId("__auto__");
      initializeMaterial(material);
      setTrainingActive(false);
      setQueue([]);
      setQueueIndex(0);
    } finally {
      setAutoLoading(false);
    }
  }, [autoTypes, initializeMaterial]);

  const selectMaterial = useCallback((materialId: string) => {
    const material = materials.find((m) => m._id === materialId);
    if (!material) return;

    setActiveMaterialId(materialId);
    setAutoEnabled(false);
    setAutoMaterial(null);
    initializeMaterial(material);
    setTrainingActive(false);
    setQueue([]);
    setQueueIndex(0);
  }, [initializeMaterial, materials]);

  const handleLeftClick = useCallback((item: string) => {
    setSelectedLeft(item);
  }, []);

  const handleRightClick = useCallback((item: string) => {
    if (!selectedLeft) return;

    // Check if this is a correct match
    const leftIndex = left.indexOf(selectedLeft);
    const material = activeMaterial;
    if (!material) return;

    const pairs = material.content?.pairs || [];
    const correctPair = pairs.find((p) => String(p.left) === selectedLeft);

    if (correctPair && String(correctPair.right) === item) {
      // Correct match
      setMatched((prev) => ({ ...prev, [selectedLeft]: item }));
      setSelectedLeft(null);
    } else {
      // Wrong match - just deselect
      setSelectedLeft(null);
    }
  }, [activeMaterial, left, selectedLeft]);

  const resetMatches = useCallback(() => {
    setMatched({});
    setSelectedLeft(null);
    setAwarded(false);
    setPoints(null);
    setScore(null);
  }, []);

  const checkCompletion = useCallback((): boolean => {
    return Object.keys(matched).length === left.length;
  }, [left.length, matched]);

  const submitAttempt = useCallback(async (): Promise<boolean> => {
    if (!activeMaterial || awarded) return false;

    const isComplete = checkCompletion();
    if (!isComplete) return false;

    const finalScore = 1.0; // All matches are correct (we only allow correct matches)

    try {
      const res = await fetch("/api/exercises/attempt", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          type: "match",
          materialId: activeMaterial._id,
          score: finalScore
        })
      });

      const data = await res.json().catch(() => ({}));

      if (res.ok) {
        setPoints(Number(data?.points || 0));
        setScore(finalScore);
        setAwarded(true);
        return true;
      }
    } catch (error) {
      console.error("Failed to submit attempt:", error);
    }

    return false;
  }, [activeMaterial, awarded, checkCompletion]);

  const startTraining = useCallback((materialIds: string[]) => {
    if (materialIds.length === 0) return;

    setQueue(materialIds);
    setQueueIndex(0);
    setTrainingActive(true);

    const firstMaterial = materials.find((m) => m._id === materialIds[0]);
    if (firstMaterial) {
      setActiveMaterialId(materialIds[0]);
      setAutoEnabled(false);
      setAutoMaterial(null);
      initializeMaterial(firstMaterial);
    }
  }, [initializeMaterial, materials]);

  const goToNextInQueue = useCallback(() => {
    if (!trainingActive || queueIndex >= queue.length - 1) return;

    const nextIndex = queueIndex + 1;
    setQueueIndex(nextIndex);

    const nextMaterial = materials.find((m) => m._id === queue[nextIndex]);
    if (nextMaterial) {
      setActiveMaterialId(queue[nextIndex]);
      initializeMaterial(nextMaterial);
      setAwarded(false);
      setPoints(null);
    }
  }, [initializeMaterial, queue, queueIndex, trainingActive, materials]);

  const goToPreviousInQueue = useCallback(() => {
    if (!trainingActive || queueIndex <= 0) return;

    const prevIndex = queueIndex - 1;
    setQueueIndex(prevIndex);

    const prevMaterial = materials.find((m) => m._id === queue[prevIndex]);
    if (prevMaterial) {
      setActiveMaterialId(queue[prevIndex]);
      initializeMaterial(prevMaterial);
      setAwarded(false);
      setPoints(null);
    }
  }, [initializeMaterial, queue, queueIndex, trainingActive, materials]);

  const exitTraining = useCallback(() => {
    setTrainingActive(false);
    setQueue([]);
    setQueueIndex(0);
  }, []);

  // Generate AI pairs
  const generateAI = useCallback(async (topic: string, pairType: "translation" | "semantic" | "definition", locale: string = "uk") => {
    setLoading(true);

    try {
      const payload = {
        exerciseType: "match",
        action: "generate",
        topic,
        pairType,
        count: 10
      };

      const res = await fetch("/api/ai/run", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          mode: "match_generate",
          userInput: JSON.stringify(payload),
          context: JSON.stringify({ uiLanguage: locale })
        })
      });

      const data = await res.json().catch(() => ({}));

      if (!res.ok) {
        setLoading(false);
        return false;
      }

      const result = JSON.parse(String(data?.text || ""));

      if (result?.task) {
        const aiMaterial: MatchMaterial = {
          _id: `ai-${Date.now()}`,
          title: result.task.title || topic,
          level: result.task.level || "A1",
          content: {
            pairs: result.task.pairs || [],
            shuffle: true,
            source: "ai"
          }
        };

        setMaterials([aiMaterial]);
        setActiveMaterialId(aiMaterial._id);
        setAutoEnabled(false);
        setAutoMaterial(null);
        initializeMaterial(aiMaterial);
        setTrainingActive(false);
        setQueue([]);
        setQueueIndex(0);
        setLoading(false);
        return true;
      }

      setLoading(false);
      return false;
    } catch (error) {
      console.error("Failed to generate AI match:", error);
      setLoading(false);
      return false;
    }
  }, [initializeMaterial]);

  return {
    // State
    materials,
    activeMaterial,
    activeMaterialId,
    left,
    right,
    selectedLeft,
    matched,
    awarded,
    points,
    score,
    loading,
    trainingActive,
    queue,
    queueIndex,
    autoEnabled,
    autoLoading,
    autoMaterial,
    autoTypes,
    autoLastUsed,

    // Actions
    loadMaterials,
    loadAutoGenerated,
    selectMaterial,
    handleLeftClick,
    handleRightClick,
    resetMatches,
    checkCompletion,
    submitAttempt,
    initializeMaterial,
    setAutoTypes,

    // Training
    startTraining,
    goToNextInQueue,
    goToPreviousInQueue,
    exitTraining,

    // AI
    generateAI
  };
}
